# Generated by Django 2.1 on 2018-08-20 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_verbose', models.CharField(max_length=100)),
                ('location_coords', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fb_url', models.URLField(blank=True, null=True)),
                ('tw_url', models.URLField(blank=True, null=True)),
                ('ig_url', models.URLField(blank=True, null=True)),
                ('galeria_urls', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='vendor_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Servicio'),
        ),
    ]
